version: '3'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    volumes:
      - ./config/elasticsearch/analysis/:/usr/share/elasticsearch/config/analysis
      - ./config/elasticsearch/storage:/usr/share/elasticsearch/data
    networks:
      - storage-network
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    volumes:
      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5600:5601
    networks:
      - storage-network

  app:
    image: search_service:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_app
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - elastic
    entrypoint: /entrypoint.sh
    labels:
      description: "search_service"
    networks:
      - storage-network

networks:
  storage-network:
    driver: bridge