# Generated by Django 2.0 on 2018-04-30 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('order', models.FloatField(default=0)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.Field')),
            ],
        ),
        migrations.CreateModel(
            name='SearchSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('search', 'Search'), ('filter', 'Filter')], default='search', max_length=10)),
                ('weight', models.IntegerField(default=0)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.Field')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('rows', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='keywordgroup',
            name='keyword_settings',
            field=models.ManyToManyField(related_name='groups', to='settings.KeywordSetting'),
        ),
    ]
