# Generated by Django 2.0 on 2018-05-03 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestsetting',
            name='key',
        ),
        migrations.AddField(
            model_name='suggestsetting',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='settings.Field'),
            preserve_default=False,
        ),
    ]
