# Generated by Django 2.0 on 2018-05-04 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20180503_0850'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuggestSetting',
            new_name='RecommendSetting',
        ),
    ]
