# Generated by Django 2.0 on 2018-05-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20180504_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('suggest_type', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('rows', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='recommendsetting',
            name='rows',
        ),
    ]
